/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Jul 14 2022
 * Processor: AT89C51
 * Aamir
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
sbit rd = P3^6;
sbit rt = P3^7;
sbit pin = P3^2;



void fun0() interrupt 1 {
   rt = 0;	
   rt = 1;
   TH0 = 0xF8;
   TL0 = 0x3B;
}

void f1() interrupt 3{}
void readfunc() interrupt 0 {
   pin = 1; 
   rd = 0; 
}
void main(void)
 { 
   
    IE = 0x8B; 
   TMOD = 0x21;	
   TH1 = 0xFD;
   TH0 = 0xF8;	
   TL0 = 0x3B;
   SCON = 0x40;
   PCON = 0x00;
   TR0 = 1;
  TR1 = 1;
   while (1) {
      SBUF = P1;
      while(TI == 0);
	 TI = 0;
   }
 }