/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Jul 14 2022
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 * Aamir
 */

#include <reg51.h>
#include <stdio.h>
char holder;


void func() interrupt 1 {
   TH0 = 0xF8;
   TL0 = 0x3B;
   P1 = holder;
   
}

void func1() interrupt 3 {
   
}
void main(void)
 { 
    IE = 0x8A;
   TMOD = 0x21;
   TH1 = 0xFD;
   TH0 = 0xF8;
   TL0 = 0x3B;
   SCON = 0x50;
   PCON = 0x00;
   TR0 = 1;
    TR1 = 1;
    while(1) {
   while (RI == 0);
      RI = 0;
      holder= SBUF;
 }
 }